services:
  server:
    build:
      context: '.'
      dockerfile: './applications.Dockerfile'
      network_mode: host
    volumes:
      - .:/app
    env_file:
      - './.env'
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
